version: '3.8'

# Services
services:
  # Nginx Service
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./workspace:/var/www/html/
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/ssl:/etc/nginx/ssl/
    depends_on:
      - php

  # Redis Service
  redis:
    build: 
      context: .
      dockerfile: ./.docker/redis/Dockerfile
    volumes:
      - ./.docker/redis:/data
    ports:
      - 6379:6379
    depends_on:
      - php

  # PHP Service
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    working_dir: /var/www/html/word
    volumes:
      - ./workspace:/var/www/html/
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini

  # MySQL Service
  mysql:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    